### ISSUE TITLE
Treating default (zero) as falsy values

### ISSUE THREAD

**Issue by arjunmayilvaganan** [cbroglie/mustache#42] opened 2020-05-18 06:42 UTC
Is the below the expected behaviour?
https://play.golang.org/p/FcnoGnJlwLv

I saw https://github.com/cbroglie/mustache/pull/33 and it makes me think otherwise

**Comment by cbroglie** [comment] 2020-05-18 07:55
I think your example is using an older version of the library b/c I hadn't tagged a release since #33 was merged. I've now tagged v1.1.0; with that version you should see the expected behavior.

**Closed by cbroglie** 2020-05-18 07:55 UTC

**Comment by arjunmayilvaganan** [comment] 2020-05-18 07:57
Thank you so much, Broglie.
